### ISSUE TITLE
Fix achievements page

### ISSUE THREAD

**Issue by AshwAthi8** [Team-Shakti/Team-Shakti.github.io#54]
- [x] remove image from the heading part.
- [x] update contact part
- [x] colour change for light blue section (choose a lighter colour of the dark blue used)
- [x] remove hyperlink from each image
- [x] remove empty image spaces(only add text if no image is not there)
- [x] reduce the size of each section

**Comment by AshwAthi8** [comment]
@meenakshisl

**Comment by meenakshisl** [comment]
Ok

**Comment by AshwAthi8** [comment]
@m0n574 and @geethna have done the 1st two parts.
