### ISSUE TITLE
Fix About.html

### ISSUE THREAD

**Issue by AshwAthi8** [Team-Shakti/Team-Shakti.github.io#56]
- [x] create a division for just heading 
- [x] add the rest part in the lighter theme

**Comment by AshwAthi8** [comment]
Currently the whole page is in darker theme with particle js in the background. Only heading should be in this portion, same as other pages the content has to be added in the lighter theme.

**Comment by AshwAthi8** [comment]
@m0n574

**Comment by m0n5742** [comment]
Done
